SENTIMENT_MIN_SCORE = -0.1
SENTIMENT_MAX_SCORE = 0.1
SENTIMENT_MIN_CONFIDENCE = 0.0
SENTIMENT_MAX_CONFIDENCE = 1.0

TAG_MIN_RELEVANCE_SCORE = 0.0
TAG_MAX_RELEVANCE_SCORE = 1.0

RELIABILITY_MIN_SCORE = 0.0
RELIABILITY_MAX_SCORE = 1.0
